# Generated by Django 3.2.9 on 2022-01-13 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Holder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('SUBJECT', 'Subject'), ('UNIVERSITY', 'University'), ('STREAM', 'Stream'), ('COURSE', 'Course'), ('SEMESTER', 'Semester')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('query', models.CharField(max_length=500)),
            ],
        ),
    ]
