# Generated by Django 3.2.9 on 2022-02-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='semester',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='stream',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='subject',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='university',
            name='slug',
            field=models.SlugField(),
        ),
    ]
