# Generated by Django 3.2.9 on 2022-01-13 15:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0001_initial_fk'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Title of the document', max_length=50)),
                ('path', models.CharField(help_text='Path where the document is stored in cloud storage', max_length=200)),
                ('author', models.ForeignKey(help_text='User info who is author of this document', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(help_text='Course to which the document is related', on_delete=django.db.models.deletion.CASCADE, related_name='course', to='services.holder')),
                ('semester', models.ForeignKey(help_text='Semester to which the document is related', on_delete=django.db.models.deletion.CASCADE, related_name='semester', to='services.holder')),
                ('stream', models.ForeignKey(help_text='Stream to which the document is related', on_delete=django.db.models.deletion.CASCADE, related_name='stream', to='services.holder')),
                ('subject', models.ForeignKey(help_text='Subject to which the document is related', on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='services.holder')),
                ('university', models.ForeignKey(help_text='University to which the document is related', on_delete=django.db.models.deletion.CASCADE, related_name='university', to='services.holder')),
            ],
        ),
    ]
