# Generated by Django 3.2.6 on 2021-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='course',
            field=models.CharField(help_text='Course to which the document is related', max_length=50),
        ),
    ]
