# Generated by Django 3.2.6 on 2021-11-07 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_alter_document_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='name',
            field=models.CharField(help_text='Title of the document', max_length=50),
        ),
    ]
